FROM ruby:2.3-slim

RUN gem install bundler

RUN apt-get update && apt-get install -y \
     build-essential \
     locales nodejs \
     libpq-dev wget lsb-release

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list

RUN apt-get update && apt-get install -y postgresql-client-12

RUN mkdir /bundle
ENV BUNDLE_PATH /bundle

WORKDIR /app

COPY run_rails.sh /
CMD ["/run_rails.sh"]
