head-fi-FI:
  keys:
    - :site_updated_at
    - :url
  options:
    expires_in: 300

header-fi-FI:
  keys:
    - :home_page
  options:
    expires_in: 300

footer-fi-FI:
  keys:
    - :create_petition_page
    - :open_petition_page
  options:
    expires_in: 300

home_page-fi-FI:
  keys:
    - :site_updated_at
    - :last_government_response_updated_at
    - :last_debate_outcome_updated_at
  options:
    expires_in: 300

local_petitions_page-fi-FI:
  keys:
    - :constituency
  options:
    expires_in: 300

all_local_petitions_page-fi-FI:
  keys:
    - :constituency
  options:
    expires_in: 300

petition-fi-FI:
  keys:
    - :petition
    - :reveal_response
    - :site_updated_at
  options:
    expires_in: 300

archived_petition-fi-FI:
  keys:
    - :petition
    - :reveal_response
    - :site_updated_at
  options:
    expires_in: 300

robots-fi-FI:
  keys:
    - :last_petition_created_at
  options:
    expires_in: 86400
    head-fi-FI:
      keys:
        - :site_updated_at
        - :url
      options:
        expires_in: 300
    
head-en-GB:
  keys:
    - :site_updated_at
    - :url
  options:
    expires_in: 300

header-en-GB:
  keys:
    - :home_page
  options:
    expires_in: 300

footer-en-GB:
  keys:
    - :create_petition_page
    - :open_petition_page
  options:
    expires_in: 300

home_page-en-GB:
  keys:
    - :site_updated_at
    - :last_government_response_updated_at
    - :last_debate_outcome_updated_at
  options:
    expires_in: 300

local_petitions_page-en-GBI:
  keys:
    - :constituency
  options:
    expires_in: 300

all_local_petitions_page-en-GB:
  keys:
    - :constituency
  options:
    expires_in: 300

petition-en-GB:
  keys:
    - :petition
    - :reveal_response
    - :site_updated_at
  options:
    expires_in: 300

archived_petition-en-GB:
  keys:
    - :petition
    - :reveal_response
    - :site_updated_at
  options:
    expires_in: 300

robots-en-GB:
  keys:
    - :last_petition_created_at
  options:
    expires_in: 86400
        
head-sv-SV:
  keys:
    - :site_updated_at
    - :url
  options:
    expires_in: 300

header-sv-SV:
  keys:
    - :home_page
  options:
    expires_in: 300

footer-sv-SV:
  keys:
    - :create_petition_page
    - :open_petition_page
  options:
    expires_in: 300

home_page-sv-SV:
  keys:
    - :site_updated_at
    - :last_government_response_updated_at
    - :last_debate_outcome_updated_at
  options:
    expires_in: 300

local_petitions_page-sv-SV:
  keys:
    - :constituency
  options:
    expires_in: 300

all_local_petitions_page-sv-SV:
  keys:
    - :constituency
  options:
    expires_in: 300

petition-sv-SV:
  keys:
    - :petition
    - :reveal_response
    - :site_updated_at
  options:
    expires_in: 300

archived_petition-sv-SV:
  keys:
    - :petition
    - :reveal_response
    - :site_updated_at
  options:
    expires_in: 300

robots-sv-SV:
  keys:
    - :last_petition_created_at
  options:
    expires_in: 86400
